### ISSUE TITLE
Cassandra 3.0 support

### ISSUE THREAD

**Issue by Daphneitec** [Symantec/ambari-cassandra-service#10]
Will it support Cassandra 3.0 (by changing the package name to dsc30)?

**Comment by ajak6** [comment]
I have not personally tested it but yes if you change the package to different version it will use that version of cassandra. I guess it will work but if there are some extra configurations available in cassandra 3.0 you will not be able to use them. If the new configurations are required then you can change the code to include those properties in cassandra.yml as well. update us if it works well.

**Comment by Daphneitec** [comment]
I have successfully upgrade to Cassandra 3.0 by changing the package name to dsc30 and the version to 3.0.
Since  dsc21 was installed before, when I try to install Cassandra 3.0 from Ambari, I have file conflicts between dsc21 and dsc30.  Since Yum won't overwrite the old dsc21 files, I have to use rpm -ifvh --replacefiles  cassandra30-xxxxxxxxx.rpm, dsc30-xxxxxxx.rpm to solve the yum install issues.
Make sure Python is upgraded to 1.7 for cqlsh and the compatible dsc30 rpm can be found locally under /var/cache/yum if needed.
