### ISSUE TITLE
 dsc21 : Depends: cassandra (= 2.1.13) but 3.0.4 is to be installed E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by trungtv** [Symantec/ambari-cassandra-service#2]
Hello, 
Could you please guide me to config preferred cassandra v3? Following is the conflict during installation.
Thank you very much 

> Traceback (most recent call last):
>   File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/CASSANDRA/package/scripts/cassandra_master.py", line 60, in <module>
>     Cassandra_Master().execute()
>   File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 219, in execute
>     method(env)
>   File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/CASSANDRA/package/scripts/cassandra_master.py", line 30, in install
>     self.install_packages(env)
>   File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 404, in install_packages
>     Package(name)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 154, in **init**
>     self.env.run()
>   File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 158, in run
>     self.run_action(resource, action)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 121, in run_action
>     provider_action()
>   File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/**init**.py", line 49, in action_install
>     self.install_package(package_name, self.resource.use_repos, self.resource.skip_repos)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/apt.py", line 53, in wrapper
>     return function_to_decorate(self, name, _args[2:])
>   File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/apt.py", line 97, in install_package
>     self.checked_call_until_not_locked(cmd, sudo=True, env=INSTALL_CMD_ENV, logoutput=self.get_logoutput())
>   File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/**init**.py", line 72, in checked_call_until_not_locked
>     return self.wait_until_not_locked(cmd, is_checked=True, *_kwargs)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/**init**.py", line 80, in wait_until_not_locked
>     code, out = func(cmd, *_kwargs)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
>     result = function(command, *_kwargs)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
>     tries=tries, try_sleep=try_sleep)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
>     result = _call(command, **kwargs_copy)
>   File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 291, in _call
>     raise Fail(err_msg)
> resource_management.core.exceptions.Fail: Execution of '/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21' returned 100. Reading package lists...
> Building dependency tree...
> Reading state information...
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dsc21 : Depends: cassandra (= 2.1.13) but 3.0.4 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ajak6** [comment]
This stack is coded to support cassandra 2.1, if the  configurations are almost same for 3.0 , you can try to change metainfo.xml with the rpm name for cassandra 3.0. Remove dsc21 in package tag.

**Comment by trungtv** [comment]
Thanks
